### PR TITLE
For compatibility

### PR DESCRIPTION
**Pull request by TotoR115**

### CODE REVIEW

**Comment by TotoR115** [comment]
https://github.com/InfinityMods/LongerRoadEE/issues/4#issuecomment-1286079686

**Comment by ALIENQuake** [comment]
Fantastic work, thank you! One question I must ask: the readme indicates that "This mod is no more compatible with Vanilla game ...". Was it neccessary? The release of LR 2.0 version was created by Austin87, especially in order to restore compatibility with the vanilla game and I would not want to make his work to be lost.

**Comment by TotoR115** [comment]
To be more precise : it is compatible with obg2 and ee, but not without ascension. I will rewritte the readme if it is not clear. 

Vanilla here means unmodded game

**Comment by ALIENQuake** [comment]
Yes, that part is confusing, I will rewrite is to be more precise. Thanks again!

**Pull request merged**
